import { create } from "zustand";

export const THEMES = {
  dark: {
    name: "Dark",
    bg: "bg-slate-900",
    sidebarBg: "bg-slate-800/50",
    headerBg: "bg-slate-800/50",
    primary: "cyan",
    secondary: "slate",
    accent: "cyan-500",
    text: "text-slate-200",
    border: "border-slate-700/50",
    borderColor: "border-slate-700/50",
    inputBg: "bg-slate-800/50",
    chatBubbleSent: "bg-cyan-600",
    chatBubbleReceived: "bg-slate-800",
    buttonPrimary: "bg-cyan-500 hover:bg-cyan-600",
    buttonSecondary: "bg-slate-700 hover:bg-slate-600",
    chatItemBg: "bg-cyan-500/10 hover:bg-cyan-500/20",
    iconButton: "text-slate-400 hover:text-slate-200",
    tabActive: "bg-cyan-500/20 text-cyan-400",
    tabInactive: "text-slate-400",
  },
  rose: {
    name: "Rose Love",
    bg: "bg-rose-50",
    sidebarBg: "bg-rose-100/30",
    headerBg: "bg-rose-100/50",
    primary: "rose",
    secondary: "rose",
    accent: "rose-500",
    text: "text-rose-900",
    border: "border-rose-200",
    borderColor: "border-rose-200",
    inputBg: "bg-rose-50",
    chatBubbleSent: "bg-rose-500",
    chatBubbleReceived: "bg-rose-100",
    buttonPrimary: "bg-rose-500 hover:bg-rose-600",
    buttonSecondary: "bg-rose-200 hover:bg-rose-300",
    chatItemBg: "bg-rose-500/10 hover:bg-rose-500/20",
    iconButton: "text-rose-400 hover:text-rose-600",
    tabActive: "bg-rose-500/20 text-rose-600",
    tabInactive: "text-rose-400",
  },
  purple: {
    name: "Royal Purple",
    bg: "bg-purple-950",
    sidebarBg: "bg-purple-900/50",
    headerBg: "bg-purple-900/50",
    primary: "purple",
    secondary: "purple",
    accent: "purple-500",
    text: "text-purple-100",
    border: "border-purple-700/50",
    borderColor: "border-purple-700/50",
    inputBg: "bg-purple-900/30",
    chatBubbleSent: "bg-purple-600",
    chatBubbleReceived: "bg-purple-800",
    buttonPrimary: "bg-purple-600 hover:bg-purple-700",
    buttonSecondary: "bg-purple-700 hover:bg-purple-600",
    chatItemBg: "bg-purple-500/10 hover:bg-purple-500/20",
    iconButton: "text-purple-300 hover:text-purple-100",
    tabActive: "bg-purple-500/20 text-purple-300",
    tabInactive: "text-purple-400",
  },
  ocean: {
    name: "Ocean Blue",
    bg: "bg-blue-950",
    sidebarBg: "bg-blue-900/50",
    headerBg: "bg-blue-900/50",
    primary: "blue",
    secondary: "blue",
    accent: "blue-500",
    text: "text-blue-100",
    border: "border-blue-700/50",
    borderColor: "border-blue-700/50",
    inputBg: "bg-blue-900/30",
    chatBubbleSent: "bg-blue-600",
    chatBubbleReceived: "bg-blue-800",
    buttonPrimary: "bg-blue-600 hover:bg-blue-700",
    buttonSecondary: "bg-blue-700 hover:bg-blue-600",
    chatItemBg: "bg-blue-500/10 hover:bg-blue-500/20",
    iconButton: "text-blue-300 hover:text-blue-100",
    tabActive: "bg-blue-500/20 text-blue-300",
    tabInactive: "text-blue-400",
  },
  sunset: {
    name: "Sunset",
    bg: "bg-orange-950",
    sidebarBg: "bg-orange-900/50",
    headerBg: "bg-orange-900/50",
    primary: "orange",
    secondary: "orange",
    accent: "orange-500",
    text: "text-orange-100",
    border: "border-orange-700/50",
    borderColor: "border-orange-700/50",
    inputBg: "bg-orange-900/30",
    chatBubbleSent: "bg-orange-600",
    chatBubbleReceived: "bg-orange-800",
    buttonPrimary: "bg-orange-600 hover:bg-orange-700",
    buttonSecondary: "bg-orange-700 hover:bg-orange-600",
    chatItemBg: "bg-orange-500/10 hover:bg-orange-500/20",
    iconButton: "text-orange-300 hover:text-orange-100",
    tabActive: "bg-orange-500/20 text-orange-300",
    tabInactive: "text-orange-400",
  },
  forest: {
    name: "Forest",
    bg: "bg-green-950",
    sidebarBg: "bg-green-900/50",
    headerBg: "bg-green-900/50",
    primary: "green",
    secondary: "green",
    accent: "green-500",
    text: "text-green-100",
    border: "border-green-700/50",
    borderColor: "border-green-700/50",
    inputBg: "bg-green-900/30",
    chatBubbleSent: "bg-green-600",
    chatBubbleReceived: "bg-green-800",
    buttonPrimary: "bg-green-600 hover:bg-green-700",
    buttonSecondary: "bg-green-700 hover:bg-green-600",
    chatItemBg: "bg-green-500/10 hover:bg-green-500/20",
    iconButton: "text-green-300 hover:text-green-100",
    tabActive: "bg-green-500/20 text-green-300",
    tabInactive: "text-green-400",
  },
  midnight: {
    name: "Midnight",
    bg: "bg-slate-950",
    sidebarBg: "bg-slate-900/70",
    headerBg: "bg-slate-900/70",
    primary: "indigo",
    secondary: "slate",
    accent: "indigo-500",
    text: "text-slate-100",
    border: "border-slate-800/50",
    borderColor: "border-slate-800/50",
    inputBg: "bg-slate-900/50",
    chatBubbleSent: "bg-indigo-600",
    chatBubbleReceived: "bg-slate-800",
    buttonPrimary: "bg-indigo-600 hover:bg-indigo-700",
    buttonSecondary: "bg-slate-800 hover:bg-slate-700",
    chatItemBg: "bg-indigo-500/10 hover:bg-indigo-500/20",
    iconButton: "text-slate-300 hover:text-slate-100",
    tabActive: "bg-indigo-500/20 text-indigo-300",
    tabInactive: "text-slate-400",
  },
};

export const useThemeStore = create((set, get) => ({
  currentTheme: localStorage.getItem("chatify_theme") || "dark",

  setTheme: (themeName) => {
    if (THEMES[themeName]) {
      localStorage.setItem("chatify_theme", themeName);
      set({ currentTheme: themeName });
    }
  },

  getTheme: () => {
    const themeName = get().currentTheme;
    return THEMES[themeName] || THEMES.dark;
  },

  getAvailableThemes: () => {
    return Object.entries(THEMES).map(([key, value]) => ({
      id: key,
      ...value,
    }));
  },
}));
